### ISSUE TITLE
LocalWeather.Callbacks()

### ISSUE THREAD

**Issue by LeeDroid-** [interaapps/LocalWeather-Android#1]
Hi,

A great implementation of the Open weather API.

With google recently shutting down awareness I had to go looking for a lightweight alternative to use in Shortcutter.

I have attempted to use your library but new LocalWeather.Callbacks() gives me an error as its not public in your library.

This was based on a straight copy and paste from your example as a starting point.

Thanks 

Lee

**Comment by DatL4g** [comment]
Hey, 
thanks for this Issue!

I'll look into later this day.

**Comment by DatL4g** [comment]
should be fixed now

**Comment by LeeDroid-** [comment]
Excellent, will give it a go tonight 👍

**Comment by LeeDroid-** [comment]
new LocalWeather.Callbacks() is still throwing is not public and cannot be accessed from outside package.

Did you re-build and push to the report and are you bumping to v1.1?

**Comment by DatL4g** [comment]
Ohh yes I forgot to start the CI

You can now take the **1.1**

**Comment by LeeDroid-** [comment]
No problem, thanks very much & thanks for the handy little implementation.

Any plans to add the ability to be able to update weather info in the
background without the use of an activity?

**Comment by DatL4g** [comment]
Not right now.
But I wanted to change a bit anyway and I would take a look at it afterwards
